// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMzNOI_9Q6GdsuBIau1hbq2wUIUHjWbeQ',
    appId: '1:397488693:web:3f1be852d7d77ce7a0377c',
    messagingSenderId: '397488693',
    projectId: 'sigmapos-13',
    authDomain: 'sigmapos-13.firebaseapp.com',
    storageBucket: 'sigmapos-13.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPyj82ueokSwBKRSqGp0tNr_mXaD17k0Y',
    appId: '1:397488693:android:4f3ab784d4fc8e05a0377c',
    messagingSenderId: '397488693',
    projectId: 'sigmapos-13',
    storageBucket: 'sigmapos-13.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0BkoQleLibtiV_r9u2XrrZh-aTcs04c0',
    appId: '1:397488693:ios:919e9a4182810518a0377c',
    messagingSenderId: '397488693',
    projectId: 'sigmapos-13',
    storageBucket: 'sigmapos-13.appspot.com',
    iosClientId: '397488693-qg1kbjdkips1bvh3tviet5fk6vj4sb20.apps.googleusercontent.com',
    iosBundleId: 'com.example.sigmaPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0BkoQleLibtiV_r9u2XrrZh-aTcs04c0',
    appId: '1:397488693:ios:919e9a4182810518a0377c',
    messagingSenderId: '397488693',
    projectId: 'sigmapos-13',
    storageBucket: 'sigmapos-13.appspot.com',
    iosClientId: '397488693-qg1kbjdkips1bvh3tviet5fk6vj4sb20.apps.googleusercontent.com',
    iosBundleId: 'com.example.sigmaPos',
  );
}
